// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BurnISO(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function FormatUSB(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<string>>;

export function ListUSB():Promise<Array<Record<string, string>>>;

export function OpenFileDialog():Promise<string>;
