// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BurnISO(arg1, arg2) {
  return window['go']['main']['App']['BurnISO'](arg1, arg2);
}

export function FormatUSB(arg1, arg2) {
  return window['go']['main']['App']['FormatUSB'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListUSB() {
  return window['go']['main']['App']['ListUSB']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
